{{- if and .Values.ingress.enabled (eq .Values.ingress.controllerType "traefik") .Values.ingress.traefik.tlsStore.enabled }}
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
